name: Deploy website

on:
  push:
    branches:
      - source-ru

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - run: npm install
      - run: npm run build

      - name: Deploy
        # Use the SHA because I am untrustworthy
        # TODO: We probably should fork any non-GitHub owned actions
        uses: peaceiris/actions-gh-pages@1828d864aeb7ba79a37f40035aa6d0b7ff66254f
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
